### ISSUE TITLE
Polynomial factorization

### ISSUE THREAD

**Issue by musicman3320** [musicman3320/m2r#9]

**Comment by dkahle** [comment]
```r
# factor a polynomial
(factors <- m2("
R = QQ[x]
f = x^3 - x^2
factor f
"))
mp(str_split(factors, "\\*")[[1]])
```

**Comment by sommars** [comment]
I coded up an initial version of this feature. However, I don't know how best to return the result to the user. Beyond returning a string, I can't think of anything reasonable. The suggestion of using
```
mp(str_split(factors, "\\*")[[1]])
```
doesn't seem like it will work, because it will fail in cases where the polynomial doesn't entirely factor, e.g.
```
> mp(str_split("4*x1^4-4*x2^4+1", "\\*")[[1]])
4
x1^4  -  4
x2^4  +  1
```
If either of you have any suggestions, I'd be happy to implement, but for now, I'm closing this issue.

**Comment by musicman3320** [comment]
Perhaps as a list of polynomial objects?  Alternatively, as a list of pairs of a polymomials and an exponent?

**Comment by sommars** [comment]
It would take more than that though. How are the list of polynomials related? It would need to be a list of polynomial objects and operators. I can't picture how a user would find that useful.

**Comment by musicman3320** [comment]
Maybe I am misunderstanding what `factor()` is supposed to do.  Won't it just be a product of polynomial objects?

**Comment by sommars** [comment]
Ok, I think I misunderstood how Macaulay2 would factor. I assumed that if you called `factor( (x+y)(x-y) + 1)` that it would return `(x+y)(x-y) + 1`. That was incorrect (it returns `x^2 - y^2 + 1`). Now that I'm thinking about it, it would be ridiculous for it to return  `(x+y)(x-y) + 1`. I'll clean it up and get it to return a list of mpolys.
